### ISSUE TITLE
[BUG] All weapons are "untrained"

### ISSUE THREAD

**Issue by hellbringer616** [Sponge-RPG-dev/NT-RPG#103]
Attacking with any class in Snapshot-7 prevents any damage and gives the following message
"You are not trained to use that item" despite the item being within both the Itemsgroup.conf and defined in the class.
log file:
https://pastebin.com/mvtjyHNf

**Comment by NeumimTo** [comment]
Could you re-test this? I cannot reproduce the issue with recent versions

**Comment by hellbringer616** [comment]
I'll check after work; I re did my itemgroups.conf and only have Daggers and Swords; which were definitely working before API 2.0.0 release.

So i removed maces; and custom armors.

**Comment by hellbringer616** [comment]
So i resolved the "untrained" issue... but i am no longer doing any damage

**Comment by hellbringer616** [comment]
resolved that; i thought i was using a vanilla item; i was not...

Must have been a config bug from something as it's all working now...
