### ISSUE TITLE
Skill cast cancellation or additional checks for skill cast

### ISSUE THREAD

**Issue by GlassSpirit** [Sponge-RPG-dev/NT-RPG#110]
A way to cancel skill cast inside script (that would lead to no mana consumed or cooldown started) or add additional checks for skill cast

**Comment by NeumimTo** [comment]
Notes to myself 
https://github.com/Sponge-RPG-dev/NT-RPG/blob/class-refactor/Plugin/src/main/java/cz/neumimto/rpg/persistance/SkillTreeDao.java#L231

Configuration could look like
```
Preprocessors: [
      {
           __class__: cz.neumimto.skills.preprocessors.conditions.CasterHasEffect
           effect_name: "effectid"
           condition_met: continue
           condition_not_met: abort
       }
)
```

+ make load skilltrees via ObjectMapper

**Comment by GlassSpirit** [comment]
Would be great if there were “scripted” preprocessor, so I can check for any condition

**Comment by NeumimTo** [comment]
- create two types of skill pre/post processors 

1) may be cached per player,  and is recreated every time player levels up, upgrades skill,  changes attribute.  The final skill setting node value is also cached.  Eg calling "param("node",_context)" should be O(1) 

2) may not be cached per player and each skill execution requires a new execution context. Those are preprocessors which modify skill settings.

**Comment by NeumimTo** [comment]
What would be an appropriate way to cancell the skill casting? 
Theres not much options in minecraft

**Comment by GlassSpirit** [comment]
I want a way to make additional checks before skill cast, that would lead to skill not being executed and no mana taken
