### ISSUE TITLE
Default class in class group

### ISSUE THREAD

**Issue by GlassSpirit** [Sponge-RPG-dev/NT-RPG#129]
Currently when you connect to the server with default configuration a character (with same name as player is automatically created) and you have no class.
Maybe something like “Default: Human” config option inside class groups config file would be good. And it would set default class on character creation automatically.

That could be used for example if you have class group Race and you want all players to be Humans (to add default effects, stats, etc).

**Comment by NeumimTo** [comment]
Currently in each class you can set node "Default":true which makes desired class default. 

This feature should be moved out of class files, to Settings.conf

**Comment by NeumimTo** [comment]
In Settings.conf
```

{
    Primary {
      PrimaryColor: Color
      SecondaryColor: Color
      DyeColor: Color
      Changeable: false
      Order: 1
      DefaultClass: Test  #Default class for the class type "primary". The parameter is optional
    }
    Secondary {
      PrimaryColor: Color
      SecondaryColor: Color
      DyeColor: Color
      Changeable: false
      Order: 1
    }
}
```
