### ISSUE TITLE
[BUG] JS skills cannot be run unless using nadmin

### ISSUE THREAD

**Issue by hellbringer616** [Sponge-RPG-dev/NT-RPG#131]
Version: NT-RPG 2.0.0-RC7
SpongeForge: spongeforge-1.12.2-2768-7.1.5
Forge: 1.12.2-2768
latest.log: https://pastebin.com/84Q64MTB
Debug.log: https://pastebin.com/nWRyyvZG

when using Javascript skills as the player, you are unable to cast them using `/skill skillid:skillname` however using `/nadmin skill skillid:skillname` works fine.

**to recreate this issue download the following:**
[JS File](https://github.com/hellbringer616/Strix-The-Realm/blob/master/config/nt-rpg/scripts/Itemizer.js)
[skill.conf file:](https://github.com/hellbringer616/Strix-The-Realm/blob/master/config/nt-rpg/addons/bronzecraft.conf)
[Itemizer.conf](https://github.com/hellbringer616/Strix-The-Realm/blob/master/config/itemizer/items.conf)

Create a class and skilltree that runs any of the skills in the conf file, and attempt to use them in game.
the game will return `no matching pattern 'skillid:skillname' present for skill!`

running the same skill as nadmin will function normally.

downloading the NT-RPG folder from [here](https://github.com/hellbringer616/Strix-The-Realm/tree/master/config/nt-rpg) will provide all of the needed files removing the need to make a class with the exception of the itemizer file linked above.

**Comment by NeumimTo** [comment]
fixed in rc8 
https://github.com/Sponge-RPG-dev/NT-RPG/releases/tag/2.0.0-RC-8
