### ISSUE TITLE
[BUG] enterCommands not working when joining classes

### ISSUE THREAD

**Issue by hellbringer616** [Sponge-RPG-dev/NT-RPG#132]
Version: NT-RPG 2.0.0-RC8
SpongeForge: spongeforge-1.12.2-2838-7.1.7-RC3928
Forge: 1.12.2-2838

When joining a class that has the  `EnterCommands:[]` section filled out; the commands do not run; the example below is suppose to force the player to join the classes: Armorer, Combat, Metallurgy, and Weaponsmith; however the commands do not run upon joining the class.
```
EnterCommands: [
    "nadmin invoke {{player}} char choose class armorer"
    "nadmin invoke {{player}} char choose class combat"
    "nadmin invoke {{player}} char choose class metallurgy"
    "nadmin invoke {{player}} char choose class weaponsmith"
]
```

To recreate the issue:

add any command to the class to run upon joining to the EnterCommand:[] section of the class config, load the server and join the class.

**Comment by NeumimTo** [comment]
Will be fixed in 2.1.0 
Also a new command added /nadmin add-class player classname which shall be used instead of hacky nadmin invoke 

https://github.com/Sponge-RPG-dev/NT-RPG/commit/1744dd6b274c0819ab828812038920a58f4ac18d
