### ISSUE TITLE
Add the functionality for server wide experience boosts. 

### ISSUE THREAD

**Issue by robertBreese** [Sponge-RPG-dev/NT-RPG#162]
Please add the functionality for server wide experience boosts. Based on percentages, maybe can be given to only certain players as well with a command modifier otherwise it's global.

**Comment by NeumimTo** [comment]
Best option is to use luckperms meta data. That way server owners can do scheduling/ automatic expiration, per-world rates, interop with different plugins, handle on their side with minimal effort on ntrpg side

 For example

ntrpg.exp.mult.pve = 2.5 

Would increase experience gain by 250%
