### ISSUE TITLE
Optional configuration for a skill - required items for skill casting

### ISSUE THREAD

**Issue by NeumimTo** [Sponge-RPG-dev/NT-RPG#22]
- Search for items only in hotbar
- Configuration whenever the item should be consumed after casting
- Check for custom item names/lore

- Optionally  configure what will happen if player has not enought items 
   - Increased manacost
   - Skill consumes casters health instead of mana
   - Apply global effect on caster

**Comment by hellbringer616** [comment]
Would love to have this feature; it's right in line with my RPG-Craft idea i am working on.

**Comment by NeumimTo** [comment]
This is quite easy addition, ill look at it after i finish implementation of class requirements for items

**Comment by NeumimTo** [comment]
There could be  a similar configuration but items needed for either learning a skill, or upgrading a skill

**Comment by NeumimTo** [comment]
Done
