### ISSUE TITLE
Use potion effects for skills for the less tech savvy

### ISSUE THREAD

**Issue by hellbringer616** [Sponge-RPG-dev/NT-RPG#33]
A suggestion:
The Laborus plugin (sadly on hiatus) let admins configure skills using potion effects; basically set a potion type, potency, and duration; for the use in skills.

Example:
**potionEffect {**
        **ambiance=false**
        _# the amplifier of the effect, see http://minecraft.gamepedia.com/Commands#effect_
        **amplifier=2**
        _# the duration of the effect, see http://minecraft.gamepedia.com/Commands#effect_
        **duration=1200**
        _# if particles are shown_
        **particles=true**
        _# the name of the type of the potion, see http://minecraft.gamepedia.com/Data_values#Status_effects names_
        **potionType="minecraft:haste"
    }**

If you added a feature like this it would likely make your plugin more accessible for the less programming savvy.

**Comment by NeumimTo** [comment]
Hi!
Good idea, but ... 
The plugin currently wont work well with vanilla potion effects such as extra damage/or resistance. 
I implemented new mechanics which affects the way how is the damage dealt or taken calculated, and i have a bit different plans for potions overall.. i simply want to create an addon into ntrpg which will allow you to define new types of potions (think of drinkable mana potion for example/posions etc) but so far im short on time and making this more user friendly and bug free has priority.

Should be quite easy to implement for potions such as invisibility, blindness, nausea, slowness, speed and others which do not manipulate damage output/input even with javascript.

**Comment by hellbringer616** [comment]
I see, would it be too much of a chore or wasted effort to implement it just for skills/effects that have not been created yet?
Or do you pretty much have everything created in your provided skills pack already?

**Comment by NeumimTo** [comment]
This is quite easy to implement with current scripting system. 



 - create js bindings for 
  - org.spongepowered...PotionEffectType
  - org.spongepowered...PotionEffectBuilder

- add new functions:

  - `milliseconds_to_server_ticks(milliseconds)`
  - `apply_potion_effect(IEffectConsumer, PotionEffectBuilder)`

**Comment by NeumimTo** [comment]
Implemented as

    var builder = potion_effect_builder("potioneffectid")
    builder.particles(true).duration(....)....
    add_potion_effect(entity, builder)
