### ISSUE TITLE
Store custom item data in the database.

### ISSUE THREAD

**Issue by NeumimTo** [Sponge-RPG-dev/NT-RPG#84]
Entire sponge api data and the way they are meant to be implemented is the most retarded thing i have ever seen. 

The way sponge data api needs to be used to achieve what i need is quite and time consuming to manage.

- Store items in the database. 
- For each item there will be only one property - item id / item uuid

- Item resolving strategies: 
  - Cache - loads all items from db into server's memory.
     - sync lookup
     - easy to implement
  - Lazy  - only when the item is needed
    - async lookup
    - loads item data when needed, 
    - still will have a small cache as FIFO, its size will be configurable. 
    - Fetch item data during: 
       - player joins - checks for all items in inventory/all items in active slots (?)
       - player picksup an item - check for that one single item

**Comment by hellbringer616** [comment]
Might not be worth it to you, but perhaps you could rework the sponge custom item code in sponge itself.
