### ISSUE TITLE
Arrow damage not calculated correctly/ignored

### ISSUE THREAD

**Issue by hellbringer616** [Sponge-RPG-dev/NT-RPG#93]
When using a bow and firing a normal minecraft arrow defined damage is not used, damage is defaulted to 10.
Log: https://pastebin.com/FR7useKQ

To recreate this issue:
1.) Define damage for `"minecraft:arrow"` under `ProjectileDamage: {}` within a race or class config
2.) Load up server and fire an arrow at any target, regardless of damage defined within the class or race config files you will do 10 damage.

**Comment by NeumimTo** [comment]
Appears to be fixed in 2.0.0
