### ISSUE TITLE
More experience sources

### ISSUE THREAD

**Issue by hellbringer616** [Sponge-RPG-dev/NT-RPG#95]
Taken from a conversation on the Discord:

Implement additional sources for experience gain such as: 
Planting seeds/trees and harvesting plants (requested by Discord user)

Additional ideas i thought of were:
Crafting items.
Catching Fish.

**Comment by NeumimTo** [comment]
FIshing is good idea, but i dislike crafting. each mod comes with a new tools and new types of crating tables it would be too time consuming for me to manage crafting in a modded environment. 
Experience sources can be added via thirdparty plugins, so i wont implement crafting directly to ntrpg.
