### ISSUE TITLE
Additional data sync for characters

### ISSUE THREAD

**Issue by GlassSpirit** [Sponge-RPG-dev/NT-RPG#96]
How about storing each character inventory in a database? And some additional data, like quests, custom values, maybe permissions or statistics, defined by addons or dependant plugins.
I mainly want this to implement “multi-server map”, where quests from customNpcs, inventories and other things are syncronized between servers connected to same database.
Health , mana, classes and other things are already stored in database, so why not store other things?

**Comment by NeumimTo** [comment]
If any other plugin wishes to use hibernate for custom data storage it can already to do so. The only requirement is to register jpa entities before hibernate starts up.  

Quests and permissions should be handled in other plugins.  For example luckperms already uses database for persistence.

The issue will be that for example luckperms will manage permissions per player.  But i assume that you would prefer to manage permissions per character?

**Comment by GlassSpirit** [comment]
And what about inventories? It would be great if there will be easier way to store any data, attached to character, than registering new entities in jpa. Maybe something like a configuration node stored in a single heavy database entry named “additional_data”, in which you may store serialized iteimstacks, nbt trees and etc.
I know it may be very bad for performance to store a lot of text in single entry of relational database, but something like that would be nice

**Comment by hellbringer616** [comment]
https://ore.spongepowered.org/BrainStone/Inventory-Sync

A plugin to sync inventory with a database, if this does what you need it to.

**Comment by NeumimTo** [comment]
@GlassSpirit My point is that creating JPA entities is so trivial task already i dont see a reason why anything like this should be part of the core plugin. 

The only thing which wont be possible is bidirectional mapping, which is always rather questionable practice. https://docs.jboss.org/hibernate/orm/4.1/manual/en-US/html/ch07.html


    @Entity
    @Table("character_inventory)
    public class CharacterInventory {
    
         @Id (+id generator annotations)
         private Long id;

         @OneToOne
         @JoinColumn(name = "character_id)
         private CharacterBase

         @Column(name = "inv_data")
         private String serializedInv
    //
      }

Then for retrieving data from underlying database you can either use 

https://github.com/Sponge-RPG-dev/NT-RPG/blob/class-refactor/Plugin/src/main/java/cz/neumimto/rpg/persistance/DirectAccessDao.java 

or simply do 

    import cz.neumimto.core.PersistentContext;
    import cz.neumimto.core.Repository;
    import cz.neumimto.core.dao.GenericDao;

    @Singleton
    @Repository
    public class CharacterInvDao extends GenericDao<CharacterInventory> {}

**Comment by NeumimTo** [comment]
I'm closing this, as you can simply use Hibernate and JPA and implement this feature, if needed.
