### ISSUE TITLE
Bug: breaking a weapon doesn't update damage output

### ISSUE THREAD

**Issue by GlassSpirit** [Sponge-RPG-dev/NT-RPG#97]
How to reproduce bug : 
1) Choose a class or race that can use for example wooden sword with 4 damage
2) Break the item (attack mobs for some time)
3) Damage is still 4 with empty hand in that slot
If you change slot or relogin, everything is back to normal.

**Comment by hellbringer616** [comment]
I think this is related to being an empty hand.

If you login and hit something with your hand, you cannot do any damage.

**Comment by NeumimTo** [comment]
@GlassSpirit would you mind opening a pr + some testing? 
all you should need to do is invalidate weapon damage cache when item breaks. 

DamageService#recalculateCharacterDamage

**Comment by GlassSpirit** [comment]
Seems like spongeApi doesn't have "item breaking" event...

**Comment by NeumimTo** [comment]
i tought its DropItemEvent.Destruct
